trainer:
  max_epochs: 15
  batch_size_per_device: 2
  wandb_project_name: 'speech-JAX'
  epochs_save_dir: 'final-960h'
  logging_steps: 64
  max_steps_per_epoch: 10

optax:
  lr: 3e-5
  weight_decay: 1e-2
  init_lr: 0.0
  warmup_steps: 16053 # 5351 * 3
  num_steps: 80265 # 5351 * 15

datacollator:
  mask_time_prob: 0.05
  mask_time_span: 15
  min_masks: 20
  audio_maxlen: 384000
  text_maxlen: 384

data:
  streaming: true
  name: librispeech_asr
  train: [clean.train.100, clean.train.360, other.train.500]
  validation: [clean]

model:
  pretrained_id: facebook/wav2vec2-large-lv60

